language: ruby
rvm:
  - 1.9.2
bundler_args: --without development
before_script:
  - "ln -s mongoid.yml.example config/mongoid.yml"
  - "ln -s omniauth.yml.example config/omniauth.yml"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export SPEC_OPTS='--no-drb --format doc'"